[package]
name = "proyecto1_SO_MultidsplayAnimator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="0.2.63"
rand = "0.8.4"